#!/usr/bin/env python3
"""Write Section 2 LaTeX fragments from data/pep_baseline.yaml.

Table 2.1's A3 column is computed from locked milestones, activity dates,
costs and resource caps. Do not re-type those cells in 02_overview.tex.

    python3 scripts/export_section2.py
"""
from __future__ import annotations

import argparse
from datetime import date, datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = ROOT / "data" / "pep_baseline.yaml"
OUT = ROOT / "sections" / "generated"

HANDOVER_DAYS = 5
PAD_TEST_BUFFER_DAYS = 15


def D(s) -> date:
    if isinstance(s, datetime):
        return s.date()
    if isinstance(s, date):
        return s
    return date.fromisoformat(str(s))


def load():
    with YAML_PATH.open() as f:
        return yaml.safe_load(f)


def aud(n) -> str:
    return f"\\${int(round(n)):,}".replace(",", "{,}")


def day_mon(d) -> str:
    d = D(d)
    return f"{d.day}~{d.strftime('%b')}"


def day_mon_year(d) -> str:
    d = D(d)
    return f"{d.day}~{d.strftime('%b')}~{d.year}"


def tex_escape(s: str) -> str:
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("#", "\\#")
        .replace("_", "\\_")
    )


def a3_cell(row: dict, data: dict) -> str:
    if row.get("a3"):
        return row["a3"]
    key = row["key"]
    proj = data["project"]
    acts = {a["id"]: a for a in data["activities"]}
    miles = data["milestones"]
    if key == "m4":
        return (
            f"\\textbf{{M-4 locked to {day_mon_year(miles['M4']['date'])}}} "
            f"(A-123 $EF$)."
        )
    if key == "m8":
        return (
            f"\\textbf{{M-8 = {day_mon_year(miles['M8']['date'])}}} (A-144)."
        )
    if key == "cost":
        return (
            f"Bottom-up \\textbf{{{aud(proj['base_estimate'])}}} + "
            f"\\textbf{{{aud(proj['contingency'])}}} contingency "
            f"(residual EMV {aud(proj['emv_sum'])} $+$ RES {aud(proj['res_allowance'])})."
        )
    if key == "permits":
        return (
            f"Facility licence already held ({data['charter']['facility_licence']}). "
            f"\\textbf{{A-113 gates A-133 static fire, not stacking.}} "
            f"Permits $EF$ {day_mon(acts['A-113']['ef'])}; "
            f"hot fire $ES$ {day_mon(acts['A-133']['es'])}."
        )
    if key == "juru":
        ch = data["charter"]
        return (
            f"Same power/interest ({ch['juru_power_interest']}, "
            f"{ch['juru_strategy']}). "
            f"\\textbf{{Embedded monitors with stop-work authority}} "
            f"and a cultural hold point before WDR (A-114 $\\to$ A-132)."
        )
    if key == "testing":
        wdr, sf = acts["A-132"], acts["A-133"]
        return (
            f"\\textbf{{A-132 WDR (cold) {day_mon(wdr['es'])}--{day_mon(wdr['ef'])}, "
            f"then A-133 static fire {day_mon(sf['es'])}--{day_mon(sf['ef'])}.}} "
            f"LRR waits on A-134 diagnostics."
        )
    if key == "risk":
        n = len(data["risks"])
        return (
            f"\\textbf{{{n} campaign-specific risks}}, Cause / Event / Effect columns, "
            f"EMV {aud(proj['emv_sum'])} + RES {aud(proj['res_allowance'])}."
        )
    if key == "resource":
        return (
            f"Organic crew \\textbf{{{proj['organic_crew']}}} named heads "
            f"({', '.join(data['resource_model']['organic_names'])}), "
            f"pad HSE cap \\textbf{{{proj['hse_pad_cap']}}}, "
            f"unmitigated peak \\textbf{{{proj['unmitigated_peak']}}}, "
            f"mitigated peak \\textbf{{{proj['mitigated_peak']}}}."
        )
    raise KeyError(f"no A3 generator for charter_refinements key {key}")


def change_table(data: dict) -> str:
    rows = []
    for row in data["charter_refinements"]:
        rows.append(
            f"\\textbf{{{tex_escape(row['element'])}}} & "
            f"{row['a1']} & "
            f"{a3_cell(row, data)} & "
            f"{row['why']} \\\\"
        )
    colspec = (
        r"@{}>{\raggedright\arraybackslash}p{2.35cm}"
        r" >{\raggedright\arraybackslash}p{4.05cm}"
        r" >{\raggedright\arraybackslash}p{4.25cm}"
        r" >{\raggedright\arraybackslash}p{4.05cm}@{}"
    )
    header = (
        "Project element & A1 charter (Week 4) & A3 PEP (Week 11) & Why it changed \\\\"
    )
    return (
        "% Generated by scripts/export_section2.py — do not edit by hand.\n"
        "{\\footnotesize\n"
        "\\setlength{\\tabcolsep}{2.6pt}\n"
        "\\renewcommand{\\arraystretch}{1.02}\n"
        f"\\begin{{longtable}}{{{colspec}}}\n"
        "\\caption[Charter baseline versus PEP refinement]{Charter baseline versus PEP refinement. A1 wording is the Week~4 "
        "charter. A3 dates and dollars are the locked YAML values used in "
        "Tables~\\ref{tab:precedence}, \\ref{tab:wbs-cost} and \\ref{tab:risk-register}.}\n"
        "\\label{tab:charter-pep}\\\\\n"
        "\\toprule\n"
        f"{header}\n"
        "\\midrule\n"
        "\\endfirsthead\n"
        "\\caption[]{Charter baseline versus PEP refinement (continued).}\\\\\n"
        "\\toprule\n"
        f"{header}\n"
        "\\midrule\n"
        "\\endhead\n"
        "\\bottomrule\n"
        "\\endfoot\n"
        + "\n".join(rows)
        + "\n\\end{longtable}\n"
        "}\n"
    )


def render(data) -> dict[str, str]:
    return {str(OUT / "s2_change_table.tex"): change_table(data)}


def identities(data) -> list[str]:
    """YAML-only identities used to build Table 2.1."""
    errors: list[str] = []
    acts = {a["id"]: a for a in data["activities"]}
    miles = data["milestones"]
    proj = data["project"]
    ch = data["charter"]
    if D(miles["M4"]["date"]) != D(acts["A-123"]["ef"]):
        errors.append("M-4 must equal A-123 EF")
    if D(miles["M8"]["date"]) != D(acts["A-144"]["ef"]):
        errors.append("M-8 must equal A-144 EF")
    if (D(miles["M8"]["date"]) - D(miles["M7"]["date"])).days != HANDOVER_DAYS:
        errors.append(f"M-8 must be {HANDOVER_DAYS} days after M-7")
    if (D(miles["M5"]["date"]) - D(miles["M4"]["date"])).days != PAD_TEST_BUFFER_DAYS:
        errors.append(
            f"M-5 − M-4 must be {PAD_TEST_BUFFER_DAYS} days (pad-test buffer)"
        )
    if D(acts["A-113"]["ef"]) != date(2026, 10, 24):
        errors.append("A-113 EF must remain 24 Oct (permits gate hot fire)")
    if D(acts["A-133"]["es"]) != date(2026, 10, 25):
        errors.append("A-133 ES must remain 25 Oct")
    if D(ch["a1_m4"]) != date(2026, 10, 28):
        errors.append("A1 M-4 collision date must stay 28 Oct")
    if D(ch["a1_m8"]) != date(2026, 11, 22):
        errors.append("A1 M-8 collision date must stay 22 Nov")
    if len(data["risks"]) != 18:
        errors.append("Table 2.1 risk row expects 18 register items")
    if proj["organic_crew"] != 8 or proj["hse_pad_cap"] != 12:
        errors.append("Table 2.1 resource row expects crew 8 / cap 12")
    keys = [r["key"] for r in data["charter_refinements"]]
    expect = [
        "m4",
        "m8",
        "cost",
        "permits",
        "juru",
        "testing",
        "risk",
        "resource",
        "stakeholders",
        "success",
        "objectives",
        "lrr",
        "community_media",
        "wdr_t10",
        "ilsa_role",
        "mobilisation",
    ]
    if keys != expect:
        errors.append(f"charter_refinements keys {keys} != {expect}")
    return errors


def write(data=None) -> None:
    data = data or load()
    OUT.mkdir(parents=True, exist_ok=True)
    for path, content in render(data).items():
        Path(path).write_text(content)
        print("wrote", path)


def check(data=None) -> list[str]:
    data = data or load()
    errors = identities(data)
    for path, content in render(data).items():
        p = Path(path)
        if not p.exists():
            errors.append(f"{p} missing; run python3 scripts/export_section2.py")
            continue
        if p.read_text() != content:
            errors.append(f"{p} stale versus YAML; run python3 scripts/export_section2.py")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = load()
    if args.check:
        errors = check(data)
        if errors:
            print("FAIL")
            for e in errors:
                print(" -", e)
            return 1
        print("PASS  generated Section 2 fragments match YAML")
        return 0
    write(data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
