#!/usr/bin/env python3
"""Write Section 1 LaTeX fragments from data/pep_baseline.yaml.

The board recommendation and the three headline-risk sentences are generated
so they cannot drift from $BAC$, contingency, $T$-0 or Table 6.1.

    python3 scripts/export_section1.py
"""
from __future__ import annotations

import argparse
from datetime import date, datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = ROOT / "data" / "pep_baseline.yaml"
OUT = ROOT / "sections" / "generated"

TOP_RISKS = ["R-01", "R-12", "R-14"]


def D(s) -> date:
    if isinstance(s, datetime):
        return s.date()
    if isinstance(s, date):
        return s
    return date.fromisoformat(str(s))


def load():
    with YAML_PATH.open() as f:
        return yaml.safe_load(f)


def aud(n) -> str:
    return f"\\${int(round(n)):,}".replace(",", "{,}")


def day_month_year(d) -> str:
    d = D(d)
    return f"{d.day}~{d.strftime('%B')}~{d.year}"


def recommendation(data: dict) -> str:
    proj = data["project"]
    t0 = day_month_year(data["milestones"]["M7"]["date"])
    gate = day_month_year(data["milestones"]["M2"]["date"])
    return (
        "It is recommended that the Executive Board approve this Project Execution Plan, "
        f"baseline the campaign at {aud(proj['bac'])} AUD (inclusive of "
        f"{aud(proj['contingency'])} contingency), including the "
        f"{aud(proj['pv_at_gate1'])} of planned pad PV already on the clock by Gate~1 "
        f"on {gate} (40.2\\% of the work PMB: permitting, Juru, cleanroom, GSE, RF and "
        f"stacking in progress), lock remaining spend at that gate, and hold $T$-0 on "
        f"{t0} inside the charter's Q1~2027 outer window."
    )


def macros(data: dict) -> str:
    risks = data["executive"]["risks"]
    rec = recommendation(data)
    return (
        "% Generated by scripts/export_section1.py — do not edit by hand.\n"
        "\\newcommand{\\PEPrecommendation}{" + rec + "}\n"
        "\\newcommand{\\PEPrOiBoard}{" + risks["R-01"] + "}\n"
        "\\newcommand{\\PEPrIxBoard}{" + risks["R-12"] + "}\n"
        "\\newcommand{\\PEPrXivBoard}{" + risks["R-14"] + "}\n"
    )


def render(data) -> dict[str, str]:
    return {str(OUT / "s1_macros.tex"): macros(data)}


def identities(data) -> list[str]:
    errors: list[str] = []
    exe = data.get("executive", {})
    if exe.get("top_risks") != TOP_RISKS:
        errors.append(f"executive.top_risks {exe.get('top_risks')} != {TOP_RISKS}")
    rec = recommendation(data)
    proj = data["project"]
    if aud(proj["bac"]) not in rec or aud(proj["contingency"]) not in rec:
        errors.append("recommendation missing BAC or contingency")
    if "15~November~2026" not in rec:
        errors.append("recommendation T-0 must be 15 November 2026")
    if "Gate~1" not in rec or "Q1~2027" not in rec:
        errors.append("recommendation must lock remaining spend at Gate 1 inside Q1 2027")
    if "authorise mobilisation" in rec:
        errors.append("recommendation must not ask the Board to authorise a mobilisation already on the clock")
    if D(data["milestones"]["M7"]["date"]) != date(2026, 11, 15):
        errors.append("M-7 must remain 15 Nov 2026")
    for rid in TOP_RISKS:
        if rid not in exe.get("risks", {}):
            errors.append(f"executive.risks missing {rid}")
    r01 = exe.get("risks", {}).get("R-01", "")
    if "A-133" not in r01 or "12--14" not in r01:
        errors.append("R-01 board sentence must keep A-133 and 12--14 day recycle")
    r12 = exe.get("risks", {}).get("R-12", "")
    if "T+14" not in r12 and "T+14~s" not in r12:
        errors.append("R-12 board sentence must keep the T+14 TestFlight 1 mode")
    r14 = exe.get("risks", {}).get("R-14", "")
    if "15~November" not in r14 or "NOTAM" not in r14:
        errors.append("R-14 board sentence must keep NOTAM and 15 November")
    if "ASA" not in r14:
        errors.append("R-14 board sentence must name ASA")
    return errors


def write(data=None) -> None:
    data = data or load()
    OUT.mkdir(parents=True, exist_ok=True)
    for path, content in render(data).items():
        Path(path).write_text(content)
        print("wrote", path)


def check(data=None) -> list[str]:
    data = data or load()
    errors = identities(data)
    for path, content in render(data).items():
        p = Path(path)
        if not p.exists():
            errors.append(f"{p} missing; run python3 scripts/export_section1.py")
            continue
        if p.read_text() != content:
            errors.append(f"{p} stale versus YAML; run python3 scripts/export_section1.py")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = load()
    if args.check:
        errors = check(data)
        if errors:
            print("FAIL")
            for e in errors:
                print(" -", e)
            return 1
        print("PASS  generated Section 1 fragments match YAML")
        return 0
    write(data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
