#!/usr/bin/env python3
"""Write Section 7 LaTeX fragments from data/pep_baseline.yaml.

Tables, DoA/milestone macros, and org-chart labels must not be re-typed in
sections/07_delivery.tex. Run before pdflatex:

    python3 scripts/export_section7.py
"""
from __future__ import annotations

import argparse
import sys
from datetime import date, datetime
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
YAML_PATH = ROOT / "data" / "pep_baseline.yaml"
OUT = ROOT / "sections" / "generated"


def D(s) -> date:
    if isinstance(s, datetime):
        return s.date()
    if isinstance(s, date):
        return s
    return date.fromisoformat(str(s))


def load():
    with YAML_PATH.open() as f:
        return yaml.safe_load(f)


def aud(n) -> str:
    return f"\\${int(round(n)):,}".replace(",", "{,}")


def aud_plain(n) -> str:
    return f"{int(round(n)):,}".replace(",", "{,}")


def day_mon(d) -> str:
    d = D(d)
    return f"{d.day}~{d.strftime('%b')}"


def day_month(d) -> str:
    d = D(d)
    return f"{d.day}~{d.strftime('%B')}"


def tex_escape(s: str) -> str:
    return s.replace("&", "\\&").replace("%", "\\%")


def render(data) -> dict[str, str]:
    proj = data["project"]
    evm = data["evm"]
    gov = data["governance"]
    m4 = data["evm_m4"]
    acts = {a["id"]: a for a in data["activities"]}
    risks = {r["id"]: r for r in data["risks"]}
    miles = data["milestones"]

    r01 = risks["R-01"]
    r07 = risks["R-07"]
    onp = m4["on_plan"]
    late = m4["late_stack"]
    doa_k = evm["pm_doa_aud"] // 1000
    m4_gap = m4["pv"] - onp["ev"]

    macros = f"""% Generated by scripts/export_section7.py — do not edit by hand.
\\newcommand{{\\PEPdoaAud}}{{{aud(evm["pm_doa_aud"])}\\xspace}}
\\newcommand{{\\PEPdoaK}}{{\\${doa_k}k\\xspace}}
\\newcommand{{\\PEPdoaHours}}{{{evm["pm_doa_hours"]}\\xspace}}
\\newcommand{{\\PEPcontingency}}{{{aud(proj["contingency"])}\\xspace}}
\\newcommand{{\\PEPbase}}{{{aud(proj["base_estimate"])}\\xspace}}
\\newcommand{{\\PEPbac}}{{{aud(proj["bac"])}\\xspace}}
\\newcommand{{\\PEPoptionC}}{{{aud(proj["option_c_cost"])}\\xspace}}
\\newcommand{{\\PEPpmName}}{{{tex_escape(gov["pm_name"])}\\xspace}}
\\newcommand{{\\PEPmTwoShort}}{{{day_mon(miles["M2"]["date"])}\\xspace}}
\\newcommand{{\\PEPmFourShort}}{{{day_mon(miles["M4"]["date"])}\\xspace}}
\\newcommand{{\\PEPmFiveShort}}{{{day_mon(miles["M5"]["date"])}\\xspace}}
\\newcommand{{\\PEPmSixShort}}{{{day_mon(miles["M6"]["date"])}\\xspace}}
\\newcommand{{\\PEPmSevenShort}}{{{day_mon(miles["M7"]["date"])}\\xspace}}
\\newcommand{{\\PEPmFourLong}}{{{day_month(miles["M4"]["date"])}\\xspace}}
\\newcommand{{\\PEPmFiveLong}}{{{day_month(miles["M5"]["date"])}\\xspace}}
\\newcommand{{\\PEPmSevenLong}}{{{day_month(miles["M7"]["date"])}\\xspace}}
\\newcommand{{\\PEPgreenLo}}{{{evm["green_lo"]:.2f}}}
\\newcommand{{\\PEPgreenHi}}{{{evm["green_hi"]:.2f}}}
\\newcommand{{\\PEPamberLo}}{{{evm["amber_lo"]:.2f}}}
\\newcommand{{\\PEPredLt}}{{{evm["red_lt"]:.2f}}}
\\newcommand{{\\PEPtZeroSlip}}{{{evm["t0_slip_trigger_days"]}\\xspace}}
\\newcommand{{\\PEPrOiImpact}}{{{aud(r01["i_dollar"])}\\xspace}}
\\newcommand{{\\PEPrOiEmv}}{{{aud(r01["emv"])}\\xspace}}
\\newcommand{{\\PEPrViiImpact}}{{{aud(r07["i_dollar"])}\\xspace}}
\\newcommand{{\\PEPrViiEmv}}{{{aud(r07["emv"])}\\xspace}}
\\newcommand{{\\PEPpvmFour}}{{{aud(m4["pv"])}\\xspace}}
\\newcommand{{\\PEPpvmFournum}}{{{aud_plain(m4["pv"])}}}
\\newcommand{{\\PEPbasenum}}{{{aud_plain(proj["base_estimate"])}}}
\\newcommand{{\\PEPbacnum}}{{{aud_plain(proj["bac"])}}}
\\newcommand{{\\PEPonPlanEV}}{{{aud(onp["ev"])}\\xspace}}
\\newcommand{{\\PEPonPlanEVnum}}{{{aud_plain(onp["ev"])}}}
\\newcommand{{\\PEPonPlanAC}}{{{aud(onp["ac"])}\\xspace}}
\\newcommand{{\\PEPonPlanACnum}}{{{aud_plain(onp["ac"])}}}
\\newcommand{{\\PEPonPlanCPI}}{{{onp["cpi"]:.2f}}}
\\newcommand{{\\PEPonPlanSPI}}{{{onp["spi"]:.2f}}}
\\newcommand{{\\PEPonPlanEac}}{{{aud(onp["eac_work"])}\\xspace}}
\\newcommand{{\\PEPonPlanEacnum}}{{{aud_plain(onp["eac_work"])}}}
\\newcommand{{\\PEPonPlanIeac}}{{{aud(onp["ieac_bac"])}\\xspace}}
\\newcommand{{\\PEPonPlanIeacnum}}{{{aud_plain(onp["ieac_bac"])}}}
\\newcommand{{\\PEPlateEV}}{{{aud(late["ev"])}\\xspace}}
\\newcommand{{\\PEPlateEVnum}}{{{aud_plain(late["ev"])}}}
\\newcommand{{\\PEPlateAC}}{{{aud(late["ac"])}\\xspace}}
\\newcommand{{\\PEPlateACnum}}{{{aud_plain(late["ac"])}}}
\\newcommand{{\\PEPlateCPI}}{{{late["cpi"]:.2f}}}
\\newcommand{{\\PEPlateSPI}}{{{late["spi"]:.2f}}}
\\newcommand{{\\PEPlateEac}}{{{aud(late["eac_work"])}\\xspace}}
\\newcommand{{\\PEPlateEacnum}}{{{aud_plain(late["eac_work"])}}}
\\newcommand{{\\PEPlateIeac}}{{{aud(late["ieac_bac"])}\\xspace}}
\\newcommand{{\\PEPlateIeacnum}}{{{aud_plain(late["ieac_bac"])}}}
\\newcommand{{\\PEPlateBand}}{{{late["band"]}}}
\\newcommand{{\\PEPmFourGap}}{{{aud(m4_gap)}\\xspace}}
\\newcommand{{\\PEPpmBox}}{{%
\\textbf{{Campaign PM}}\\\\[-0.05em]\\textbf{{\\mbox{{\\PEPpmName}}}}\\\\[0.12em]
  \\scriptsize DoA: $\\le$ \\PEPdoaK{{}} \\emph{{and}} $\\le$ \\PEPdoaHours{{}}~h\\\\[-0.05em]
  \\scriptsize Cannot move M-5 (\\PEPmFiveShort) or M-7 (\\PEPmSevenShort)}}
"""

    hp_rows = []
    for hp in data["hold_points"]:
        act = acts[hp["activity"]]
        if "Ziyad" not in hp["release"]:
            raise SystemExit(f"{hp['id']} release must include Ziyad")
        hp_rows.append(
            f"{hp['id']} & {hp['activity']} ({day_mon(act['ef'])}) & {hp['risk']} & "
            f"{tex_escape(hp['name'])} & {tex_escape(hp['release'])} \\\\"
        )
    hold_colspec = r"@{}l l l >{\raggedright\arraybackslash}p{3.55cm} >{\raggedright\arraybackslash}X@{}"
    hold_tex = (
        "\\begin{table}[H]\n"
        "\\centering\n"
        "\\small\n"
        "\\caption[Quality hold points]{Quality hold points for the Bowen campaign. Each hold is a named artefact, not a meeting. "
        "Measurement rules in Section~\\ref{sec:delivery-evm} follow the same IDs.}\n"
        "\\label{tab:holdpoints}\n"
        f"\\begin{{tabularx}}{{\\textwidth}}{{{hold_colspec}}}\n"
        "\\toprule\n"
        "Hold & Activity & Risk & Artefact & Release \\\\\n"
        "\\midrule\n"
        f"{chr(10).join(hp_rows)}\n"
        "\\bottomrule\n"
        "\\end{tabularx}\n"
        "\\end{table}\n"
    )

    evm_rows = "\n".join(
        [
            f"{m4['planned_label']} & {aud_plain(m4['pv'])} & --- & --- & --- & --- & --- \\\\",
            (
                f"Illustrative on-plan & {aud_plain(m4['pv'])} & {aud_plain(m4['on_plan']['ev'])} & "
                f"{aud_plain(m4['on_plan']['ac'])} & {m4['on_plan']['cpi']:.2f} & "
                f"{m4['on_plan']['spi']:.2f} & {m4['on_plan']['action']} \\\\"
            ),
            (
                f"Illustrative late stack & {aud_plain(m4['pv'])} & {aud_plain(m4['late_stack']['ev'])} & "
                f"{aud_plain(m4['late_stack']['ac'])} & {m4['late_stack']['cpi']:.2f} & "
                f"{m4['late_stack']['spi']:.2f} & {m4['late_stack']['action']} \\\\"
            ),
        ]
    )
    evm_colspec = r"@{}>{\raggedright\arraybackslash}p{4.55cm} r r r c c X@{}"
    evm_tex = (
        "\\begin{table}[H]\n"
        "\\centering\n"
        "\\footnotesize\n"
        "\\setlength{\\tabcolsep}{4.0pt}\n"
        "\\caption[Illustrative earned-value status at M-4]{Illustrative earned-value status at M-4 ("
        f"{day_month(miles['M4']['date'])}~2026). The campaign has not been executed. "
        "PV is the locked work-PMB value at stacking complete. Indices use the reported "
        "two-decimal CPI/SPI from $EV/AC$ and $EV/PV$.}\n"
        "\\label{tab:evm-m4}\n"
        f"\\begin{{tabularx}}{{\\textwidth}}{{{evm_colspec}}}\n"
        "\\toprule\n"
        "Status at M-4 & PV & EV & AC & CPI & SPI & Action \\\\\n"
        "\\midrule\n"
        f"{evm_rows}\n"
        "\\bottomrule\n"
        "\\end{tabularx}\n"
        "\\end{table}\n"
    )

    return {
        str(OUT / "s7_macros.tex"): macros,
        str(OUT / "s7_holdpoints_table.tex"): hold_tex,
        str(OUT / "s7_evm_table.tex"): evm_tex,
    }


def write(data=None) -> None:
    data = data or load()
    OUT.mkdir(parents=True, exist_ok=True)
    for path, content in render(data).items():
        Path(path).write_text(content)
        print("wrote", path)


def check(data=None) -> list[str]:
    data = data or load()
    errors = []
    for path, content in render(data).items():
        p = Path(path)
        if not p.exists():
            errors.append(f"{p} missing; run python3 scripts/export_section7.py")
            continue
        if p.read_text() != content:
            errors.append(f"{p} stale versus YAML; run python3 scripts/export_section7.py")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    data = load()
    if args.check:
        errors = check(data)
        if errors:
            print("FAIL")
            for e in errors:
                print(" -", e)
            return 1
        print("PASS  generated Section 7 fragments match YAML")
        return 0
    write(data)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
